### ISSUE TITLE
json Data structure

### ISSUE THREAD

**Issue by eldelga** [majorsilence/CrystalCmd#29]
Hello !!! how can I convert data from sql query to dataset json. I already have a report on mssql and I want to try it the server

that's what I'm trying to do  :

`curl -u "username:password" -F "reportdata=@test.json" -F "reporttemplate=@ZXX12SBONFAC.rpt" http://127.0.0.1:2005/export --output testout2.pdf`

and this is the response I get:
`curl: (52) Empty reply from server`

Is there any posibility to connect from a SQL connection direct?

Thanks a lot

Cheers !

**Comment by majorsilence** [comment]
Please note this project is for a very specific use case and most crystal report users will be better off with https://www.sap.com/canada/products/technology-platform/crystal-server.html.

It does not connect directly to/from sql.   It is for when you have a c# client application that for some reason is better served by using another process to generate a pdf.  It is very hacky.  However, with that said, see below.

To create the json use the client library.   

- https://github.com/majorsilence/CrystalCmd/tree/main/dotnet/Majorsilence.CrystalCmd.Client
- https://www.nuget.org/packages/Majorsilence.CrystalCmd.Client

```cs
DataTable dt = ...from your code...
var reportData = new Data()
{
    DataTables = new Dictionary<string, string>(),
    MoveObjectPosition = new List<MoveObjects>(),
    Parameters = new Dictionary<string, object>()
};

// AddData can be passed a DataTable or IEnumerable
reportData.AddData("EMPLOYEE", dt);
```

To generate the pdf in c# use the Report class.

https://github.com/majorsilence/CrystalCmd/blob/main/dotnet/DotNetRunner/Program.cs#L111C1-L124C10

```cs
async Task CreatePdfFromReport(string reportPath, string pdfOutputPath, Data reportData)
        {
            Console.WriteLine($"Creating pdf {pdfOutputPath} from report {reportPath}");

            using (var fstream = new FileStream(reportPath, FileMode.Open))
            using (var fstreamOut = new FileStream(pdfOutputPath, FileMode.OpenOrCreate | FileMode.Append))
            {
                var rpt = new Report(exportUrl, username: "user", password: "password");
                using (var stream = await rpt.GenerateAsync(reportData, fstream))
                {
                    stream.CopyTo(fstreamOut);
                }
            }
        }
```
